var userInfo = {
	"userExecutionContext": null,
	"isOutboudLinkVisible": false,
	"AppURL": null,
	// "EncryptedBPC": "MzE5ODc50",
	// "Smart1PortalURL": "https://smartdev.gep.com/Portal/Dashboard/Documents?md=bT0xMyZzbT0xNQ2&oloc=101",
	// "FullName": "exxon_avAdmin",
	"JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImV4eG9ubW9iaWwuYWRtaW5AZ2VwLmNvbSIsImh0dHA6Ly93d3cuZ2VwLmNvbS9jLzIiOiIxMDEwMDAwMSwxMDEwMDAwMiwxMDEwMDAxMywxMDEwMDAxNCwxMDEwMDAxNSwxMDEwMDAxNiwxMDEwMDAxOCwxMDEwMDAxOSwxMDEwMDAyMCwxMDEwMDAyMSwxMDEwMDAyMiwxMDEwMDAyMywxMDEwMDAyNSwxMDEwMDAyNiwxMDEwMDAyOCwxMDEwMDAyOSwxMDEwMDAzMSwxMDEwMDAzMiwxMDEwMDAzMywxMDEwMDAzNCwxMDEwMDAzNSwxMDEwMDAzOCwxMDEwMDA0MCwxMDEwMDA0MSwxMDEwMDA0MiwxMDEwMDA0MywxMDEwMDA0NCwxMDEwMDA1MCwxMDMwMDAwMSwxMDMwMDAwMiwxMDMwMDAwMywxMDMwMDAwNiwxMDMwMDAyMiwxMDMwMDAzMiwxMDMwMDAzNCwxMDMwMDA1NiwxMDMwMDA2NywxMDMwMDA2OCwxMDMwMDA2OSwxMDMwMDA3MCwxMDMwMDA3MSwxMDMwMDA3MiwxMDMwMDA3MywxMDMwMDA3NCwxMDMwMDA3NSwxMDMwMDA3NiwxMDMwMDA3NywxMDQwMDAwMSwxMDQwMDAwMiwxMDQwMDAwMywxMDQwMDAwNCwxMDQwMDAwNSwxMDQwMDAwNiwxMDQwMDAwOCwxMDQwMDAwOSwxMDQwMDAxMSwxMDQwMDAxMiwxMDQwMDAxMywxMDQwMDAxNCwxMDQwMDAxNSwxMDQwMDAxNiwxMDQwMDAxNywxMDQwMDAxOCwxMDQwMDAxOSwxMDQwMDAyMCwxMDQwMDAyMSwxMDQwMDAyMiwxMDQwMDAyMywxMDQwMDAyNCwxMDQwMDAyOCwxMDQwMDAyOSwxMDQwMDAzMCwxMDUwMDAwMSwxMDUwMDAwMywxMDUwMDAxMCwxMDUwMDAxMSwxMDUwMDAyMywxMDUwMDAzMiwxMDUwMDAzNCwxMDUwMDAzNSwxMDUwMDAzNiwxMDUwMDAzNywxMDUwMDAzOCwxMDUwMDAzOSwxMDUwMDA0MCwxMDUwMDA0MSwxMDUwMDA0NCwxMDUwMDA0NSwxMDUwMDA0NiwxMDYwMDAwNiwxMDYwMDAxNCwxMDYwMDAxNiwxMDYwMDAxNywxMDYwMDAyMSwxMDYwMDAyMiwxMDYwMDAyMywxMDYwMDAyNCwxMDYwMDAyNSwxMDYwMDAyNywxMDYwMDAyOCwxMDYwMDAyOSwxMDYwMDAzMCwxMDYwMDAzMSwxMDYwMDAzNywxMDYwMDA0OCwxMDYwMDA1OCwxMDYwMDA1OSwxMDcwMDAwMSwxMDcwMDAwMywxMDcwMDAwNCwxMDcwMDAwNSwxMDcwMDAxMCwxMDcwMDAxMSwxMDcwMDAxMywxMDcwMDAxNCwxMDcwMDAxOCwxMDcwMDAyMywxMDcwMDAzMywxMDcwMDAzNCwxMDcwMDAzNywxMDcwMDAzOCwxMDcwMDAzOSwxMDcwMDA0MSwxMDcwMDA0MiwxMDcwMDA0MywxMDcwMDA0NCwxMDcwMDA0NSwxMDcwMDA0OCwxMDcwMDA0OSwxMDcwMDA1MCwxMDcwMDA1MywxMDcwMDA1NCwxMDcwMDA1NSwxMDcwMDA1NiwxMDcwMDA1NywxMDcwMDA1OCwxMDcwMDA1OSwxMDcwMDA2MCwxMDcwMDA2MSwxMDcwMDA2MiwxMDcwMDA2MywxMDcwMDA2NCwxMDcwMDA2NSwxMDcwMDA2NywxMDcwMDA2OCwxMDcwMDA2OSwxMDcwMDA3MCwxMDcwMDA3MSwxMDcwMDA3MiwxMDcwMDA3MywxMDcwMDA3NCwxMDcwMDA3NSwxMDcwMDA3NiwxMDcwMDA3NywxMDcwMDA3OCwxMDcwMDA3OSwxMDcwMDA4MCwxMDcwMDA4MiwxMDcwMDA4NSwxMDcwMDA4NiwxMDcwMDA4NywxMDcwMDA4OCwxMDcwMDA5MSwxMDcwMDA5MiwxMDcwMDA5MywxMDcwMDA5NCwxMDcwMDEwMCwxMDcwMDEwMSwxMDcwMDIwMywxMDgwMDAwMSwxMDgwMDAwMiwxMDgwMDAwNCwxMDgwMDAwNSwxMDgwMDAwNiwxMDgwMDAwNywxMDgwMDAwOCwxMDgwMDAwOSwxMDgwMDAxMCwxMDgwMDAxMSwxMDgwMDAxMiwxMDgwMDAxMywxMTMwMDAwMSwxMTMwMDAwMiwxMTMwMDAwMywxMTMwMDAwNCwxMTMwMDAwNSwxMTMwMDAwNiwxMTMwMDAwNywxMTMwMDAwOCwxMTMwMDAwOSwxMTMwMDAxMCwxMTMwMDAxMSwxMTMwMDAxMiwxMTQwMDAwMSwxMTQwMDAwMywxMTQwMDAwNCwxMTUwMDAwMSwxMTUwMDAwMiwxMTUwMDAwNCwxMTUwMDAwNSwxMTUwMDAwNiwxMTUwMDAwNywxMTUwMDAwOCwxMTUwMDAwOSwyMTYwMDAwNCwyMTYwMDAwNSwyMTYwMDAwNiwyMTYwMDAwOCwyMTYwMDAxMCwyMTYwMDAxMSwyMTYwMDAxMywyMTYwMDAxNCwyMTYwMDAxNSwyMTYwMDAxNiwyMTYwMDAyMCwyMTYwMDA0NiwzMDEwMDAwMSwzMDEwMDAwMiwzMDEwMDAwMywzMDEwMDAwNCwzMDEwMDAwNSwzMDQwMDAwMSwzMDQwMDAwMiwzMDYwMDAwMSwzMDYwMDAwMywxMTUwMDAwMTAsMTE1MDAwMDExLDExNTAwMDAxMiwxMTUwMDAwMTQsMTE1MDAwMDE1LDExNTAwMDAxNywxMTUwMDAwMTgsMTE1MDAwMDE5LDExNTAwMDAyMCwxMTUwMDAwMjEsMTE1MDAwMDIyLDExNTAwMDAyMywxMTUwMDAwMjYsMTE1MDAwMDI3LDExNTAwMDAyOCwxMTUwMDAwMjksMTE1MDAwMDMxLDExNTAwMDAzMywyNjEwMDAwMzAiLCJodHRwOi8vd3d3LmdlcC5jb20vYy8xMyI6IjIxOTczMiIsImh0dHA6Ly93d3cuZ2VwLmNvbS9jLzQiOiIzMTk4NzkwNDAwMDAwMSIsImh0dHA6Ly93d3cuZ2VwLmNvbS9jLzE1IjoiMzE5ODc5IiwiaHR0cDovL3d3dy5nZXAuY29tL2MvMTYiOiJlbi1VUyIsImh0dHA6Ly93d3cuZ2VwLmNvbS9jLzE3IjoiMSIsImh0dHA6Ly93d3cuZ2VwLmNvbS9jLzE4IjoiMTIwIiwiaHR0cDovL3d3dy5nZXAuY29tL2MvMTkiOiIxNjUuMjI1LjEwNi4xMTkiLCJodHRwOi8vd3d3LmdlcC5jb20vYy8yMSI6IjAiLCJodHRwOi8vd3d3LmdlcC5jb20vYy8yMiI6IjAiLCJodHRwOi8vd3d3LmdlcC5jb20vYy8yMyI6IkV4eG9uTW9iaWwiLCJuYmYiOjE1NTU1MDY2MTUsImV4cCI6MTU1NTUxMzgxNSwiaWF0IjoxNTU1NTA2NjE1fQ.PBSP0av-VVhkqfVrap8Yc4dntCHZhRkRdU_9pfKjnA0",
	// "ActiveSessionDuration": 120,
	// "SCAPIMSubKey": "c4e717ff0c404d23b66519bf7fa7f07e",
	"URLs": {
	  // "AppURL": "https://smartdev.gep.com/",
	  // "ContentURL": "https://gepsmartshouldcost.blob.core.windows.net/",
	  "GePServiceURL": null,
	  // "BaseURL": "https://gepdevsmart-relay.gep.com/",
	  "NodeServiceURL": null,
	  "P2PRestURL": null,
	  "GePBlobContentURL": null,
	  "ApimURL": null,
	  "SignalRUrl": null,
	  "APIBaseURL": "https://localhost/",
	  "SCLandingPage": null,
	  // "ServiceURL": "https://smartdev.gep.com/",
	  "CosmosDBURL": null,
	  "FunctionURL": null,
	  // "ShouldCostAPIURL" : "https://api-smartdev-direct.gep.com/",
	  // "WorkspaceBaseUrl": "https://smartdev.gep.com/"
	},
	"DocumentCode": 1000,
	"DocumentCodes": null,
	"APIMSubKey": "2e0329d00df24eb8a1672c9b10bf7e16",
	// "Mode": "",
	"ActivityCodes" : [30100001,30100002,30100003],
	"UserBasicDetails": {
	  "ClientName": "exxon_av Admin",
	  "UserId": 219732,
	  "ContactCode": 31987904000001,
	  "LoggerCode": "EC101",
	  "EntityId": 0,
	  "EntityType": "",
	  "Product": 9,
	  "Culture": "en-US",
	  "UserName": "exxon_av",
	  "Contexts": [],
	  "CompanyName": "BuyerSqlConn",
	  "ClientID": 319879,
	  "BuyerPartnerCode": 319879,
	  "IsAdmin": true,
	  "IsSupplier": false,
	  "IsSuperUser": false,
	  "DefaultCurrencyCode": "EUR",
	  "BelongingEntityId": 0,
	  "BelongingEntityDetailCode": 0,
	  "ServingEntityId": 0,
	  "ServingEntityDetailCode": 0,
	  "ShipToLocationId": 1,
	  "BuyerPartnerName": "ExxonMobil"
	},
	// "UnReadAnnouncementsCount": 0,
	// "ScriptVersion": null,
	// "SearchRESTEndpoint": null,
	// "UserTheme": null,
	// "SessionTimeoutInterval": 0,
	// "EncryptedParamBPC": null,
	// "encryptedBlankDocument": null,
	// "IsBuyerAdmin": false,
	// "SearchScope": null,
	// "IsRuleEngineAccess": false,
	// "IsSmartSetupAdmin": false,
	// "IsSetupImplementaion": false,
	// "IsSetupProduct": false,
	// "EncryptSupplierDD": null,
	// "UserPreferences": null,
	// "SMART2DocTypes": null,
	// "SessionGuid": "00000000-0000-0000-0000-000000000000",
	// "TenantName": null,
	// "AreaName": null,
	// "Redirect1Documentsto2": false,
	// "TypeOfUser": 0,
	// "defaultCurrencyCode": null,
	// "documentIntegrationEntity": null,
	// "NAVButtonsAccessRights": null,
	// "ClientName": null,
	// "UserName": null,
	// "TimeOffset": 0.0,
	// "TimeZoneStandardName": null,
	// "LOBHeaderEntities": null,
	// "IsMouseFlowEnabled": null,
	// "IsWhatFixEnabled": null,
	// "ShowManageInterfaceOperations": false,
	// "UserBrowsingAPIMConn": null,
	// "APIMSubscriptionKey": null,
	// "BrowserName": null,
	// "BrowserVersion": null,
	// "RegionID": "8",
	// "UserBrowsingTimeInterval": 0,
	// "IsUserBrowsingHistoryEnabled": false,
	// "isTemplateBasedQuery": false,
	// "LoginUserName": null,
	// "subAreaName": null,
	// "DataScienceLink": false,
	// "APIMBaseURL": null
  };
